### ISSUE TITLE
Plugin not loadinf Human workflows in Human 

### ISSUE THREAD

**Issue by p57p57** [mitre/human#11]
**Describe the bug**
When loading human plugin into the GUI to generate a human, there are no human workflows (Task in the error message) loaded. It is then impossible to generate a human cf. error message: Select tasks for human to execute
**To Reproduce**
1. Launch and log in to caldera.
2. Select human plugin in the list
3. scroll down to "Name... build your human"
4. set aname
5. select an OS
6. and then nothing to select for human's behavior

**Expected behavior**

`Having the set of workflows displayed in the list

**Screenshots**
![image](https://user-images.githubusercontent.com/42292696/122020430-0de07f80-cdc5-11eb-9942-0a7322cf79f7.png)

**Desktop (please complete the following information):**
 - OS: CentOS 7
 - Browser chrome
 - Version [3.1.0]

**Comment by mkultraWasHere** [comment]
@p57p57 - looking into now, sorry for delay.

**Comment by mkultraWasHere** [comment]
@p57p57 - I created a fix (https://github.com/mitre/human/pull/12) for this and then realized that there seems to already be a fix for this here: https://github.com/mitre/human/pull/10. 

@wbooth - Will the existing fix be merged or is there an issue Im not seeing?

**Comment by p57p57** [comment]
> 
> 
> @p57p57 - looking into now, sorry for delay.

 @elegantmoose  no problem, we all have many things to do :o)

**Comment by mkultraWasHere** [comment]
bumping @wbooth

**Comment by p57p57** [comment]
Hi @elegantmoose,
could you tell me when this will be merged into the master branch in order to be able to update my running version ?
Thanks in advance,
Best Regards

**Comment by p57p57** [comment]
Hi @elegantmoose,
i have tested the fix on my configuration, seems it works (at least it loads the existing workflows).

**Comment by mkultraWasHere** [comment]
@p57p57 - we are attempting to pull it in now with #12 . Standby.
