### ISSUE TITLE
How to provides custom commands ?

### ISSUE THREAD

**Issue by p57p57** [mitre/human#13]
Hi,
i would like to undertand hos to add custom commands to enrich human workflows.
Could you tell me how and where to do it because i haven't found anything about that in the documentation.

Best Regards

**Comment by blackwidow0616** [comment]
Within the GUI component of the human plugin, there is a button to add custom commands when building a human. You can then enter the custom command. When you generate the human, you should be able to see the custom commands within the code block that is output.
![Screen Shot 2021-07-14 at 2 22 42 PM](https://user-images.githubusercontent.com/38511035/125673160-a0ff0338-7d60-491c-8eae-41c82029b7c2.png)

**Comment by blackwidow0616** [comment]
Hopefully this answers your question. If you’re still having any problems, please feel free to re-open or start a new ticket. Thanks!
